[package]
name = "oss-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
oss-core = { path = "../oss-core" }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5.0"
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio-rustls"] }
dotenvy = "0.15"
inquire = "0.9.1"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
